<?php

/**
 * AudioDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AudioDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AudioDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AudioDetail');
    }
}