<?php

/**
 * BodyPartValuesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BodyPartValuesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BodyPartValuesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BodyPartValues');
    }
}