<?php

/**
 * DeviceValueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeviceValueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeviceValueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeviceValue');
    }
}