<?php

/**
 * LocationValuesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocationValuesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LocationValuesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LocationValues');
    }
}