<?php

/**
 * QolScoreValuesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QolScoreValuesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QolScoreValuesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QolScoreValues');
    }
}