<?php

/**
 * UserSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserSessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserSession');
    }
}