<?php

/**
 * ActivityRecurrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityRecurrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityRecurrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityRecurr');
    }
}