<?php

/**
 * CalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cal');
    }
}