<?php

/**
 * IncidentDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IncidentDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IncidentDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IncidentDetail');
    }
}