<?php

/**
 * IncidentChangeDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IncidentChangeDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IncidentChangeDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IncidentChangeDetail');
    }
}