<?php

/**
 * IncidentRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IncidentRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IncidentRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IncidentRecord');
    }
}