<?php

/**
 * OdViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OdViewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OdViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OdView');
    }
}